"""
Database Browser Module

Provides a visual interface for browsing and loading surgical cases from the database.
Includes:
- Case list with filtering (Date, Provider, Room)
- Camera selection dialog
- Thumbnail previews (background generation)
- Integration with main application

Created for feature: 1-multimpv-db-controls
Author: Generated by Claude Code
Date: 2026-01-12
"""

import tkinter as tk
from tkinter import ttk, messagebox, Toplevel
import sqlite3
import os
import threading
import subprocess
import tempfile
import configparser
import sys
from typing import List, Optional, Tuple, Dict
from .models import Case, CameraMetadata

# Add project root to path to import config.py (go up 3 levels: lib -> MPV_DB -> root)
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import config

class DatabaseBrowser:
    """
    GUI for browsing and selecting cases from the ScalpelDatabase.
    """

    def __init__(self, master: tk.Tk, on_load_callback):
        self.master = master
        self.on_load_callback = on_load_callback
        
        # Load config
        self.db_path, self.mpv_path = self._get_config_values()
        
        # State
        self.cases: List[Case] = []
        self.filtered_cases: List[Case] = []
        self.thumb_cache = {} # Map item_id -> PhotoImage
        self.stop_threads = False
        
        # Create Window
        self.window = Toplevel(master)
        self.window.title("Case Browser - ScalpelLab")
        self.window.geometry("900x600")
        
        # UI Components
        self._build_ui()
        
        # Initial Load
        self._refresh_cases()
        
        self.window.protocol("WM_DELETE_WINDOW", self._on_close)

    def _get_config_values(self):
        config_ini = configparser.ConfigParser()
        # Config is at MPV_DB root, go up one level from lib/
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        config_path = os.path.join(base_dir, 'config.ini')
        config_ini.read(config_path)
        
        # DB Path
        db_path = os.path.join(base_dir, "ScalpelDatabase.sqlite")
        if 'Database' in config_ini and 'database_path' in config_ini['Database']:
            configured_path = config_ini['Database']['database_path']
            if not os.path.isabs(configured_path):
                db_path = os.path.normpath(os.path.join(base_dir, configured_path))
            else:
                db_path = configured_path
            
        # MPV Path
        mpv_path = "mpv.exe"
        if 'MPV' in config_ini and 'mpv_path' in config_ini['MPV']:
            mpv_path = config_ini['MPV']['mpv_path']
            
        return db_path, mpv_path

    def _build_ui(self):
        # --- Filter Frame ---
        filter_frame = ttk.LabelFrame(self.window, text="Filter Cases", padding=10)
        filter_frame.pack(fill=tk.X, padx=10, pady=5)
        
        ttk.Label(filter_frame, text="Date (YYYY-MM-DD):").pack(side=tk.LEFT, padx=5)
        self.date_var = tk.StringVar()
        self.date_var.trace("w", self._apply_filters)
        ttk.Entry(filter_frame, textvariable=self.date_var, width=12).pack(side=tk.LEFT, padx=5)
        
        ttk.Button(filter_frame, text="Refresh", command=self._refresh_cases).pack(side=tk.RIGHT, padx=5)

        # --- Case List ---
        list_frame = ttk.Frame(self.window, padding=10)
        list_frame.pack(fill=tk.BOTH, expand=True)
        
        # Removed "room" and "duration" columns
        columns = ("thumb", "date", "case", "cameras")
        self.tree = ttk.Treeview(list_frame, columns=columns, show="headings", selectmode="browse")
        
        self.tree.heading("thumb", text="Preview")
        self.tree.heading("date", text="Date")
        self.tree.heading("case", text="Case #")
        self.tree.heading("cameras", text="Cameras")
        
        self.tree.column("thumb", width=100, anchor="center")
        self.tree.column("date", width=120)
        self.tree.column("case", width=80)
        self.tree.column("cameras", width=80)
        
        # Adjust row height for thumbnails
        style = ttk.Style()
        style.configure("Treeview", rowheight=60)
        
        self.tree.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        
        # Configure tags for alternating colors
        self.tree.tag_configure('odd', background='#F0F0F0')
        self.tree.tag_configure('even', background='#FFFFFF')
        
        scrollbar = ttk.Scrollbar(list_frame, orient=tk.VERTICAL, command=self.tree.yview)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
        self.tree.configure(yscrollcommand=scrollbar.set)
        
        self.tree.bind("<Double-1>", self._on_case_selected)
        
        # --- Bottom Bar ---
        bottom_frame = ttk.Frame(self.window, padding=10)
        bottom_frame.pack(fill=tk.X)
        
        ttk.Button(bottom_frame, text="Exit", command=self._on_close).pack(side=tk.RIGHT, padx=5)
        ttk.Button(bottom_frame, text="Open Selected Case", command=self._on_case_selected_btn).pack(side=tk.RIGHT)
        self.status_label = ttk.Label(bottom_frame, text="Ready")
        self.status_label.pack(side=tk.LEFT)

    def _refresh_cases(self):
        self.status_label.config(text="Loading cases...")
        self.window.update_idletasks()
        
        try:
            self.cases = self._load_cases_from_database()
            self._apply_filters()
            self.status_label.config(text=f"Loaded {len(self.cases)} cases.")
            
            # Start background thumbnail generation
            threading.Thread(target=self._generate_thumbnails, daemon=True).start()
            
        except Exception as e:
            messagebox.showerror("Database Error", f"Failed to load cases: {e}")
            self.status_label.config(text="Error loading cases.")

    def _generate_thumbnails(self):
        """Background thread to generate thumbnails"""
        temp_dir = os.path.join(tempfile.gettempdir(), "scalpel_thumbs")
        os.makedirs(temp_dir, exist_ok=True)
        
        # Prioritize visible cases (simple: just iterate list)
        for case in self.cases:
            if self.stop_threads: break
            
            item_id = f"{case.recording_date}_{case.case_no}"
            
            # Skip if already cached
            if item_id in self.thumb_cache:
                continue
                
            # Find a suitable video (Monitor preferred)
            monitor_cam = next((c for c in case.cameras if "Monitor" in c.camera_name and c.file_exists), None)
            target_cam = monitor_cam or next((c for c in case.cameras if c.file_exists), None)
            
            if not target_cam: continue
            
            thumb_path = os.path.join(temp_dir, f"{item_id}.png")
            
            # Generate if not exists
            if not os.path.exists(thumb_path):
                # Use MPV to extract frame at offset 10s (or 1s)
                # Resize to width 80 (height auto)
                # cmd: mpv --no-config --start=10 --frames=1 --vo=image --o=out.png --vf=scale=80:-1 video.mp4
                cmd = [
                    self.mpv_path,
                    "--no-config",
                    f"--start={max(10, target_cam.offset_seconds)}", # Try 10s or saved offset
                    "--frames=1",
                    "--vo=image",
                    f"--o={thumb_path}",
                    "--vf=scale=90:-1", # Slightly smaller than column width
                    target_cam.file_path
                ]
                
                try:
                    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
                except Exception:
                    continue
            
            # Load into Tkinter
            if os.path.exists(thumb_path):
                try:
                    # Note: PhotoImage needs main thread? Usually yes.
                    # We schedule update on main thread.
                    self.window.after(0, lambda p=thumb_path, i=item_id: self._update_thumbnail(p, i))
                except Exception:
                    pass

    def _update_thumbnail(self, path, item_id):
        """Update treeview with loaded image"""
        if self.stop_threads: return
        try:
            # Check if widget still exists to avoid "invalid command name" error
            try:
                if not self.tree.winfo_exists(): return
            except Exception:
                return

            img = tk.PhotoImage(file=path)
            self.thumb_cache[item_id] = img # Keep reference
            
            if self.tree.exists(item_id):
                self.tree.item(item_id, image=img)
        except Exception:
            # Ignore errors if window is closed/closing
            pass

    def _load_cases_from_database(self) -> List[Case]:
        if not os.path.exists(self.db_path):
            raise FileNotFoundError(f"Database not found at {self.db_path}")
            
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        query = """
            SELECT
                ms.recording_date,
                ms.case_no,
                a.name as provider,
                COUNT(ms.camera_name) as cam_count,
                MAX(ms.duration_minutes) as max_dur
            FROM mp4_status ms
            LEFT JOIN recording_details rd ON ms.recording_date = rd.recording_date AND ms.case_no = rd.case_no
            LEFT JOIN anesthesiology a ON rd.anesthesiology_key = a.anesthesiology_key
            GROUP BY ms.recording_date, ms.case_no
            ORDER BY ms.recording_date DESC, ms.case_no DESC
        """
        
        cursor.execute(query)
        rows = cursor.fetchall()
        conn.close()
        
        loaded_cases = []
        for row in rows:
            date, case_no, provider, cam_count, duration = row
            c = Case(
                recording_date=date,
                case_no=case_no,
                anesthesiologist_name=provider if provider else "Unknown",
                camera_count=cam_count if cam_count else 0,
                total_duration=(duration * 60) if duration else 0.0,
                cameras=[] 
            )
            loaded_cases.append(c)
            
        for c in loaded_cases:
            c.cameras = self._load_cameras_for_case(c.recording_date, c.case_no)
            c.camera_count = len(c.cameras)
            
        return loaded_cases

    def _load_cameras_for_case(self, date: str, case_no: int) -> List[CameraMetadata]:
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        try:
            query = """
                SELECT camera_name, path, duration_minutes, size_mb, offset_seconds
                FROM mp4_status
                WHERE recording_date = ? AND case_no = ?
            """
            cursor.execute(query, (date, case_no))
        except sqlite3.OperationalError:
            query = """
                SELECT camera_name, path, duration_minutes, size_mb, 0.0
                FROM mp4_status
                WHERE recording_date = ? AND case_no = ?
            """
            cursor.execute(query, (date, case_no))
            
        rows = cursor.fetchall()
        conn.close()
        
        cameras = []
        for row in rows:
            name, path, duration, size, offset = row
            if offset is None: offset = 0.0
            full_path = path if path else ""
            
            # Trust DB path if it exists, otherwise do minimal rebase
            exists_in_db = bool(full_path)
            
            if not full_path or not os.path.exists(full_path):
                # Only attempt rebase if path is missing or invalid on current mount
                if full_path and "DATA_" in full_path:
                    rel = full_path[full_path.find("DATA_"):]
                    rebased = os.path.join(config.MP4_ROOT, rel)
                    if os.path.exists(rebased):
                        full_path = rebased
                        exists_in_db = True

            try:
                cam = CameraMetadata(
                    camera_name=name,
                    file_path=full_path,
                    duration=(duration * 60) if duration else 0.0,
                    file_size=size if size else 0,
                    offset_seconds=offset,
                    file_exists=exists_in_db, # Use the DB-based existence
                    case_id=(date, case_no)
                )
                cameras.append(cam)
            except ValueError:
                pass
                
        return cameras

    def _apply_filters(self, *args):
        date_filter = self.date_var.get().lower()
        self.filtered_cases = [c for c in self.cases if date_filter in c.recording_date.lower()]
        
        for item in self.tree.get_children():
            self.tree.delete(item)
            
        for i, c in enumerate(self.filtered_cases):
            item_id = f"{c.recording_date}_{c.case_no}"
            
            # Check cache for thumb
            img = self.thumb_cache.get(item_id, "")
            
            tag = 'even' if i % 2 == 0 else 'odd'
            
            self.tree.insert("", tk.END, iid=item_id, values=(
                "", # Thumb column text empty
                c.recording_date, c.case_no, c.camera_count
            ), image=img, tags=(tag,))

    def _on_case_selected_btn(self):
        self._on_case_selected(None)

    def _on_case_selected(self, event):
        selection = self.tree.selection()
        if not selection: return
        item_id = selection[0]
        parts = item_id.split('_')
        selected_case = next((c for c in self.cases if c.recording_date == parts[0] and c.case_no == int(parts[1])), None)
        if selected_case: self._show_camera_selection_dialog(selected_case)

    def _show_camera_selection_dialog(self, case: Case):
        dialog = Toplevel(self.window)
        dialog.title(f"Select Cameras - Case {case.case_no}")
        dialog.geometry("500x400")
        
        ttk.Label(dialog, text="Select cameras to load:", font=("Arial", 11, "bold")).pack(pady=10)
        camera_selection_items = []
        frame = ttk.Frame(dialog)
        frame.pack(fill=tk.BOTH, expand=True, padx=20)
        
        for cam in case.cameras:
            var = tk.BooleanVar(value=True)
            camera_selection_items.append((cam, var))
            row = ttk.Frame(frame)
            row.pack(fill=tk.X, pady=2)
            cb = ttk.Checkbutton(row, text=cam.camera_name, variable=var)
            cb.pack(side=tk.LEFT)
            if cam.file_exists:
                ttk.Label(row, text="✓", foreground="green").pack(side=tk.LEFT, padx=5)
            else:
                ttk.Label(row, text="⚠️ Missing", foreground="red").pack(side=tk.LEFT, padx=5)
                var.set(False); cb.configure(state=tk.DISABLED)
                
        btn_frame = ttk.Frame(dialog, padding=10)
        btn_frame.pack(fill=tk.X)
        
        def on_load():
            selected = [cam for cam, var in camera_selection_items if var.get()]
            if not selected: messagebox.showwarning("Selection", "Select at least one camera."); return
            
            self.stop_threads = True # Stop background threads
            dialog.destroy()
            self.window.destroy() 
            self.on_load_callback(selected)
            
        ttk.Button(btn_frame, text="Load Videos", command=on_load).pack(side=tk.RIGHT)
        ttk.Button(btn_frame, text="Cancel", command=dialog.destroy).pack(side=tk.RIGHT, padx=10)

    def _on_close(self):
        self.stop_threads = True
        self.window.destroy()