"""
MPV Controller Module

Manages MPV video player processes and IPC (Inter-Process Communication) via named pipes.
This module provides a clean API for launching MPV instances, sending commands, and querying
properties without dealing with low-level subprocess and pipe management.

Created for feature: 1-multimpv-db-controls (Manual Camera Synchronization)
Author: Generated by Claude Code
Date: 2026-01-12
"""

import subprocess
import os
import time
from typing import Optional, List


class MPVController:
    """
    Controller for managing multiple MPV video player instances with IPC support.

    This class handles:
    - Launching MPV processes with named pipe IPC enabled
    - Sending commands to MPV instances (pause, seek, etc.)
    - Querying MPV properties (current timestamp, duration, etc.)
    - Cleanup and process management

    Example usage:
        controller = MPVController("C:/path/to/mpv.exe")
        process = controller.launch_video(
            video_path="F:/video.mp4",
            pipe_name="\\\\.\\pipe\\mpv_socket_0",
            geometry="640x480+0+0",
            start_offset=5.5
        )
        controller.send_command(pipe_name, "pause")
        timestamp = controller.query_property(pipe_name, "time-pos")
    """

    def __init__(self, mpv_executable_path: str):
        """
        Initialize MPV Controller.

        Args:
            mpv_executable_path: Absolute path to mpv.exe
        """
        self.mpv_exe = mpv_executable_path
        self.processes: List[subprocess.Popen] = []

        # Verify MPV executable exists
        if not os.path.exists(self.mpv_exe):
            raise FileNotFoundError(f"MPV executable not found: {self.mpv_exe}")

    def launch_video(
        self,
        video_path: str,
        pipe_name: str,
        geometry: str,
        start_offset: float = 0.0,
        keep_open: bool = True,
        force_window: bool = True,
        osc: bool = True
    ) -> subprocess.Popen:
        """
        Launch MPV instance with IPC enabled.

        Args:
            video_path: Absolute path to video file
            pipe_name: Named pipe path for IPC (Windows: \\.\\pipe\\mpv_socket_N)
            geometry: Window geometry string (WxH+X+Y, e.g., "640x480+0+0")
            start_offset: Start playback at this timestamp in seconds (default: 0.0)
            keep_open: Keep window open after video ends (default: True)
            force_window: Force window creation even if video is audio-only (default: True)
            osc: Show on-screen controller (default: True)

        Returns:
            subprocess.Popen: MPV process handle

        Raises:
            FileNotFoundError: If video file doesn't exist
            subprocess.SubprocessError: If MPV fails to launch
        """
        # Validate video file exists
        if not os.path.exists(video_path):
            raise FileNotFoundError(f"Video file not found: {video_path}")

        # Build MPV arguments
        mpv_args = [
            self.mpv_exe,
            video_path,
            f"--input-ipc-server={pipe_name}",
            f"--geometry={geometry}",
            "--idle", # Keep running even if file fails to load
        ]

        # Add start offset if positive (apply saved sync offset)
        # MPV --start cannot handle negative values or "+- " syntax
        if start_offset > 0.0:
            mpv_args.append(f"--start=+{start_offset}")

        # Add optional flags
        if keep_open:
            mpv_args.append("--keep-open=yes")
        if force_window:
            mpv_args.append("--force-window=yes")
        if osc:
            mpv_args.append("--osc=yes")

        # Launch MPV process
        try:
            print(f"DEBUG: Executing MPV: {mpv_args}")
            process = subprocess.Popen(
                mpv_args,
                stdout=subprocess.DEVNULL,
                stderr=None # Let stderr show in console for debugging
            )
            self.processes.append(process)

            # Wait for IPC pipe to be ready
            start_time = time.time()
            pipe_ready = False
            while time.time() - start_time < 5.0: # Wait up to 5 seconds
                # Check if process died
                if process.poll() is not None:
                    raise subprocess.SubprocessError(f"MPV process terminated early with code {process.returncode}")
                
                # Try to open pipe
                try:
                    # Check if pipe exists using explicit open check
                    # os.path.exists might be flaky for pipes on some windows versions
                    fd = os.open(pipe_name, os.O_RDWR)
                    os.close(fd)
                    pipe_ready = True
                    break
                except (FileNotFoundError, OSError):
                    time.sleep(0.1)
            
            if not pipe_ready:
                # Process alive but pipe not ready
                process.terminate()
                raise subprocess.SubprocessError(f"MPV started but IPC pipe {pipe_name} was not created within timeout.")

            return process

        except Exception as e:
            raise subprocess.SubprocessError(f"Failed to launch MPV: {e}")

    def send_command(self, pipe_name: str, command: str) -> bool:
        """
        Send command to MPV via IPC (fire-and-forget).

        Args:
            pipe_name: Named pipe path
            command: MPV command string (e.g., "pause", "seek -1.0 relative+exact")

        Returns:
            bool: True if command sent successfully, False if error occurred

        Examples:
            send_command(pipe, "pause")                      # Toggle pause
            send_command(pipe, "set pause yes")              # Explicit pause
            send_command(pipe, "seek -1.0 relative+exact")   # Seek backward 1s
            send_command(pipe, "frame-step")                 # Advance 1 frame
            send_command(pipe, "set speed 0.5")              # Half speed
        """
        try:
            fd = os.open(pipe_name, os.O_RDWR)
            os.write(fd, (command + '\n').encode('utf-8'))
            os.close(fd)
            return True
        except FileNotFoundError:
            print(f"[IPC Error] Named pipe not found: {pipe_name}")
            return False
        except BrokenPipeError:
            print(f"[IPC Error] MPV process terminated (broken pipe)")
            return False
        except Exception as e:
            print(f"[IPC Error] Failed to send command: {e}")
            return False

    def query_property(self, pipe_name: str, property_name: str, timeout_ms: int = 500) -> Optional[str]:
        """
        Query MPV property via IPC (blocking with timeout).
        Handles mixed output (JSON events + text response).
        """
        try:
            fd = os.open(pipe_name, os.O_RDWR)
            command = f"get_property {property_name}\n"
            os.write(fd, command.encode('utf-8'))

            expected_prefix = f"ANS_{property_name}="
            start_time = time.time()
            buffer = ""
            
            while (time.time() - start_time) * 1000 < timeout_ms:
                try:
                    # Read chunk
                    chunk = os.read(fd, 4096).decode('utf-8', errors='ignore')
                    if not chunk:
                        time.sleep(0.01)
                        continue
                    
                    buffer += chunk
                    lines = buffer.split('\n')
                    
                    # Process lines
                    for line in lines:
                        line = line.strip()
                        if not line: continue
                        
                        if line.startswith(expected_prefix):
                            os.close(fd)
                            return line.split('=', 1)[1]
                        
                        # Debug: Check if it's an error or unexpected non-event
                        if not line.startswith("{") and not line.startswith("ANS_"):
                            # Only print true garbage, ignore JSON events
                            # print(f"[IPC Debug] Ignored: {line}")
                            pass
                            
                    # Keep partial last line if not ending in newline
                    if not buffer.endswith('\n'):
                        buffer = lines[-1]
                    else:
                        buffer = ""
                        
                except BlockingIOError:
                    time.sleep(0.01)
                    continue
                except Exception:
                    break
            
            os.close(fd)
            return None

        except FileNotFoundError:
            # Common race condition when closing app, suppress noise
            return None
        except BrokenPipeError:
            return None
        except Exception as e:
            print(f"[IPC Error] Failed to query property {property_name}: {e}")
            return None

    def close_all(self):
        """
        Terminate all MPV processes managed by this controller.

        This method attempts graceful termination first, then force-kills
        processes that don't respond within 1 second.
        """
        for process in self.processes:
            if process.poll() is None:  # Process still running
                try:
                    process.terminate()  # Graceful termination
                    process.wait(timeout=1.0)  # Wait up to 1 second
                except subprocess.TimeoutExpired:
                    process.kill()  # Force kill if still running
                except Exception as e:
                    print(f"[Warning] Error closing MPV process: {e}")

        self.processes.clear()

    def __del__(self):
        """Cleanup: Close all MPV processes when controller is destroyed"""
        self.close_all()


# Helper functions for common commands

def pause_all(controller: MPVController, pipes: List[str]):
    """Send pause command to all MPV instances"""
    for pipe in pipes:
        controller.send_command(pipe, "pause")


def play_all(controller: MPVController, pipes: List[str]):
    """Resume playback on all MPV instances"""
    for pipe in pipes:
        controller.send_command(pipe, "set pause no")


def seek_all(controller: MPVController, pipes: List[str], seconds: float):
    """Seek all MPV instances by specified seconds (relative)"""
    for pipe in pipes:
        controller.send_command(pipe, f"seek {seconds} relative+exact")


def set_speed_all(controller: MPVController, pipes: List[str], speed: float):
    """Set playback speed for all MPV instances"""
    for pipe in pipes:
        controller.send_command(pipe, f"set speed {speed}")

    # Mute audio if speed != 1.0x (avoid pitch distortion)
    if speed != 1.0:
        for pipe in pipes:
            controller.send_command(pipe, "set ao-volume 0")
    else:
        for pipe in pipes:
            controller.send_command(pipe, "set ao-volume 100")
