"""
Parquet File Inspector for Pose Keypoints

This script opens and displays the contents of parquet files generated by 1_pose_anesthesiologist.py
"""

import sys
import os
import json
import pandas as pd
import numpy as np


def load_config():
    """Load configuration from 0_yolo_config.json"""
    config_path = os.path.join(os.path.dirname(__file__), "0_yolo_config.json")

    if not os.path.exists(config_path):
        return None

    with open(config_path, 'r') as f:
        config = json.load(f)

    return config


def inspect_parquet(parquet_path):
    """
    Inspect and display contents of a parquet file.

    Args:
        parquet_path: Path to the parquet file
    """
    print("\n" + "=" * 70)
    print("PARQUET FILE INSPECTOR")
    print("=" * 70)
    print(f"File: {parquet_path}")

    # Check if file exists
    if not os.path.exists(parquet_path):
        print(f"ERROR: File not found: {parquet_path}")
        sys.exit(1)

    # Get file size
    file_size = os.path.getsize(parquet_path) / (1024 * 1024)
    print(f"File Size: {file_size:.2f} MB")
    print("=" * 70)

    # Load parquet file
    print("\nLoading parquet file...")
    df = pd.read_parquet(parquet_path)

    # Basic information
    print("\n" + "=" * 70)
    print("BASIC INFORMATION")
    print("=" * 70)
    print(f"Number of rows: {len(df)}")
    print(f"Number of columns: {len(df.columns)}")
    print(f"Memory usage: {df.memory_usage(deep=True).sum() / (1024 * 1024):.2f} MB")

    # Column information
    print("\n" + "=" * 70)
    print("COLUMNS")
    print("=" * 70)
    print(df.columns.tolist())

    # Data types
    print("\n" + "=" * 70)
    print("DATA TYPES")
    print("=" * 70)
    print(df.dtypes)

    # First few rows
    print("\n" + "=" * 70)
    print("FIRST 10 ROWS")
    print("=" * 70)
    print(df.head(10))

    # Basic statistics
    print("\n" + "=" * 70)
    print("BASIC STATISTICS")
    print("=" * 70)
    print(df.describe())

    # Check for missing values
    print("\n" + "=" * 70)
    print("MISSING VALUES")
    print("=" * 70)
    missing_counts = df.isnull().sum()
    missing_pct = (missing_counts / len(df)) * 100
    missing_df = pd.DataFrame({
        'Column': missing_counts.index,
        'Missing Count': missing_counts.values,
        'Missing %': missing_pct.values
    })
    missing_df = missing_df[missing_df['Missing Count'] > 0].sort_values('Missing Count', ascending=False)

    if len(missing_df) > 0:
        print(missing_df.to_string(index=False))
    else:
        print("No missing values found!")

    # Frame and timestamp info
    print("\n" + "=" * 70)
    print("FRAME & TIMESTAMP INFO")
    print("=" * 70)
    if 'Frame_ID' in df.columns:
        print(f"First Frame ID: {df['Frame_ID'].min()}")
        print(f"Last Frame ID: {df['Frame_ID'].max()}")
        print(f"Total Frames: {df['Frame_ID'].nunique()}")

    if 'Timestamp' in df.columns:
        print(f"Start Time: {df['Timestamp'].min():.2f} seconds")
        print(f"End Time: {df['Timestamp'].max():.2f} seconds")
        print(f"Duration: {df['Timestamp'].max() - df['Timestamp'].min():.2f} seconds")

    # Track ID info
    if 'Track_ID' in df.columns:
        print("\n" + "=" * 70)
        print("TRACK ID INFO (Multi-Person Tracking)")
        print("=" * 70)
        unique_tracks = df['Track_ID'].nunique()
        total_detections = len(df)
        print(f"Unique persons tracked: {unique_tracks}")
        print(f"Total detections (all persons): {total_detections}")
        print(f"Average detections per person: {total_detections/unique_tracks:.1f}")

        # Show distribution of detections per track ID (Top 10)
        print("\nDetections per Track ID (Top 10):")
        track_counts = df['Track_ID'].value_counts().head(10)
        for track_id, count in track_counts.items():
            pct = (count / total_detections) * 100
            print(f"  Track {int(track_id):3d}: {count:5d} detections ({pct:5.1f}%)")

        # Show track IDs present
        track_ids = sorted(df['Track_ID'].unique())
        print(f"\nAll Track IDs: {[int(t) for t in track_ids]}")

    # Keypoint detection statistics
    print("\n" + "=" * 70)
    print("KEYPOINT DETECTION STATISTICS")
    print("=" * 70)

    # Count frames with detected keypoints (check if Nose_conf > 0)
    if 'Nose_conf' in df.columns:
        detected_frames = (df['Nose_conf'] > 0).sum()
        detection_rate = (detected_frames / len(df)) * 100
        print(f"Frames with detection: {detected_frames}/{len(df)} ({detection_rate:.1f}%)")
        print(f"Frames without detection: {len(df) - detected_frames}/{len(df)} ({100-detection_rate:.1f}%)")

        # Average confidence for each keypoint
        print("\n" + "=" * 70)
        print("AVERAGE KEYPOINT CONFIDENCE (when detected)")
        print("=" * 70)

        keypoint_names = [
            "Nose", "Left_Eye", "Right_Eye", "Left_Ear", "Right_Ear",
            "Left_Shoulder", "Right_Shoulder", "Left_Elbow", "Right_Elbow",
            "Left_Wrist", "Right_Wrist", "Left_Hip", "Right_Hip",
            "Left_Knee", "Right_Knee", "Left_Ankle", "Right_Ankle"
        ]

        for kp_name in keypoint_names:
            conf_col = f"{kp_name}_conf"
            if conf_col in df.columns:
                # Only calculate mean for detected keypoints (conf > 0)
                detected_vals = df[df[conf_col] > 0][conf_col]
                if len(detected_vals) > 0:
                    avg_conf = detected_vals.mean()
                    detection_count = len(detected_vals)
                    detection_pct = (detection_count / len(df)) * 100
                    print(f"{kp_name:20s}: {avg_conf:.3f} (detected in {detection_count}/{len(df)} frames, {detection_pct:.1f}%)")
                else:
                    print(f"{kp_name:20s}: N/A (never detected)")

    print("\n" + "=" * 70)
    print("INSPECTION COMPLETE")
    print("=" * 70)


def main():
    """Main entry point"""
    # Load config to get default parquet path
    config = load_config()
    default_parquet_path = None
    if config and "output" in config and "parquet_path" in config["output"]:
        default_parquet_path = config["output"]["parquet_path"]

    if len(sys.argv) > 1:
        parquet_path = sys.argv[1].strip('"').strip("'")
    else:
        if default_parquet_path:
            print(f"\nDefault parquet path from config: {default_parquet_path}")
            print("Press Enter to use default, or enter a different path:")
            user_input = input("Parquet path: ").strip().strip('"').strip("'")
            parquet_path = user_input if user_input else default_parquet_path
        else:
            print("\nEnter the path to the parquet file:")
            parquet_path = input("Parquet path: ").strip().strip('"').strip("'")

    if not parquet_path:
        print("ERROR: No file path provided")
        sys.exit(1)

    inspect_parquet(parquet_path)


if __name__ == "__main__":
    main()
