"""Validate the composed OLD-MP4 -> SEQ -> NEW-MP4 frame mapping.

The OLD MP4s under ``D:\\Rec_Backup`` were generated by an earlier exporter
(``C:\\Users\\user\\Downloads\\exporters\\old.py``) that did:

    ffmpeg -hwaccel cuda -r 30 -i <seq> -c:v h264_nvenc ... <out.mp4>

No IDX consultation, no ``tpad`` pre-roll, no ``fps=30`` resampling filter,
no group-wide alignment. There is also a CLExport fallback path used on
ffmpeg failure. That makes ``old_mp4_frame_index == seq_frame_index`` a
plausible BUT UNVERIFIED hypothesis.

The NEW MP4s under ``MP4_ROOT`` are produced by
``scripts/3_seq_to_mp4_convert.py`` via an IDX-driven mkvmerge VFR ->
``-vf fps=30`` ffmpeg pipeline with ``tpad start=<pre_roll>`` and a group
target duration. For a SEQ frame ``K`` the NEW MP4 frame index is

    f(K) = pre_roll + round((t_seq[K] - t_seq[0]) * 30)

So the round-trip from an annotation timed against the OLD MP4 to the
corresponding NEW MP4 frame is the composition ``j_new = f(g(i_old))``,
where ``g`` is the unknown OLD-MP4 -> SEQ frame mapping that this script
is trying to identify.

Hypotheses for g(i_old) = K_seq
================================
    g_identity         : K = i_old
    g_fps_scale_30     : K = round(i_old * source_fps / 30)
                         (OLD MP4 nominally 30 fps via ``-r 30``, SEQ runs
                         at source_fps from IDX timestamps)
    g_fps_scale_oldfps : K = round(i_old * source_fps / old_fps)
                         (uses ffprobe's reported OLD fps -- catches the
                         case where the ``-r 30`` flag didn't actually
                         produce a 30.000 fps output)
    g_shift_plus1      : K = i_old + 1
    g_shift_minus1     : K = i_old - 1
                         (off-by-one from ffmpeg's SEQ demuxer consuming
                         SPS/PPS as a synthetic first frame, etc.)
    g_pre_roll         : K = i_old - pre_roll
                         (would only matter if the OLD pipeline trimmed
                         leading frames; included for completeness)
    g_linear           : K = round(a*i_old + b)
                         (fitted per camera from observed best matches;
                         appended at runtime, see _fit_learned_linear)

Algorithm (per camera)
======================
For each anchor frame i_old in the OLD MP4 (evenly spaced, edges trimmed):

  1. Extract OLD anchor frame at t = i_old / old_fps -> dHash -> h_old.
  2. For each hypothesis above compute K_pred and then j_pred = f(K_pred).
  3. Scan K over [i_old - SEARCH_RADIUS_SEQ, i_old + SEARCH_RADIUS_SEQ]
     (default +/- 30 SEQ frames ~ +/- 1s at source_fps). For each K
     compute j = f(K) and Hamming(h_old, dHash(NEW frame j)). The K with
     the smallest Hamming is K_empirical -- the dHash-derived truth that
     each closed-form hypothesis is graded against.
  4. dHash(SEQ frame K) is approximated by dHash(NEW MP4 frame f(K)). This
     means the entire validator stays in MP4 space (one cheap ffmpeg
     burst per anchor) and reuses the same 256-bit dHash as the rest of
     the helpers. Caveat: if f itself is mis-mapping a frame in the NEW
     pipeline, the error is attributed to g rather than f. The
     ``min_hamming_local`` column for g_identity remains a sanity check
     on f's correctness.
  5. Per anchor and per hypothesis, report:
       * K_pred, j_pred
       * Hamming at j_pred, min Hamming within j +/- LOCAL_RADIUS
       * best j-offset within that window
       * residual_K = K_pred - K_empirical

A hypothesis is CONFIRMED for a camera if, across the anchors:
  * min_hamming_local is consistently <= GOOD_THRESHOLD bits (default 16)
  * j_pred is consistently the local Hamming minimum on the NEW MP4 side
    (median best_offset within +/- 1 frame)

The residual_K column is reported as a diagnostic but is NOT used to
gate the verdict, because surgical scenes are near-static and the
empirical-K argmin is noise dominated -- many nearby K values give
indistinguishable dHash on a quasi-still frame.

This is a validation tool, not a remapper. No CSV merge with the main
report; this prints a per-camera table and optionally writes JSON/CSV
dumps for the run.
"""

from __future__ import annotations

import argparse
import io
import json
import shutil
import sqlite3
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

# Stdout UTF-8 on Windows console.
if hasattr(sys.stdout, "buffer") and (sys.stdout.encoding or "").lower() not in ("utf-8", "utf8"):
    sys.stdout = io.TextIOWrapper(
        sys.stdout.buffer, encoding="utf-8", errors="replace", line_buffering=True
    )

_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))

try:
    from config import get_db_path, get_seq_root, get_mp4_root  # type: ignore
except ImportError:
    get_db_path = lambda: str(_PROJECT_ROOT / "ScalpelDatabase.sqlite")  # type: ignore
    get_seq_root = lambda: r"F:\Room_8_Data\Sequence_Backup"  # type: ignore
    get_mp4_root = lambda: r"F:\Room_8_Data\Recordings"  # type: ignore


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
TARGET_FPS = 30
GROUP_A = ("Cart_Center_2", "Cart_LT_4", "Cart_RT_1", "General_3")
GROUP_B = ("Monitor", "Patient_Monitor", "Ventilator_Monitor")
SOLO_CAMERAS = ("Injection_Port",)

DEFAULT_OLD_ROOT = r"D:\Rec_Backup"

_IDX_RECORD_SIZE = 32          # bytes per IDX record
_IDX_UINT32_PER_RECORD = 8     # 32 bytes = 8 uint32s
_IDX_U32_TS_SEC = 3            # ts_sec at uint32 index 3
_IDX_U32_TS_SUB = 4            # ts_sub at uint32 index 4

# Same dHash geometry as align_old_new_mp4.py.
_DHASH_W, _DHASH_H = 17, 16
_DHASH_BITS = (_DHASH_W - 1) * _DHASH_H       # 256
_DHASH_BYTES = _DHASH_W * _DHASH_H            # 272

# Confirmation thresholds.
_GOOD_THRESHOLD_BITS = 16      # min Hamming <= this -> dHash match plausible
_RESIDUAL_K_TOLERANCE = 1      # |K_pred - K_empirical| <= 1 -> hypothesis confirmed
_BEST_OFFSET_TOLERANCE = 1     # best j-offset within +/-1 of predicted -> tight fit

# Default radius for the K-space empirical search around i_old (in SEQ
# frames). Exposed via --search-radius-seq.
_DEFAULT_SEARCH_RADIUS_SEQ = 30

# Hypothesis verdict: CLExport fallback heuristic. If every closed-form
# hypothesis fails AND the empirical search still finds a clean dHash
# match somewhere, the OLD MP4 was probably generated by a different
# code path (CLExport, an older ffmpeg, etc.).
_CLEXPORT_FLAG_THRESHOLD_BITS = 20

# Epoch sanity gate for IDX timestamps.
_EPOCH_MIN = 1_420_070_400
_EPOCH_MAX = 1_924_905_600


# ---------------------------------------------------------------------------
# IDX parser
# ---------------------------------------------------------------------------
def parse_idx_timestamps(idx_path: Path) -> np.ndarray | None:
    """Return per-frame Unix timestamps (float64) from a .seq.idx file."""
    if not idx_path.exists():
        return None
    try:
        raw = idx_path.read_bytes()
    except OSError:
        return None
    n_records = len(raw) // _IDX_RECORD_SIZE
    if n_records == 0:
        return None
    u32 = np.frombuffer(raw[: n_records * _IDX_RECORD_SIZE], dtype="<u4")
    ts_sec = u32[_IDX_U32_TS_SEC :: _IDX_UINT32_PER_RECORD][:n_records].astype(np.float64)
    ts_sub = u32[_IDX_U32_TS_SUB :: _IDX_UINT32_PER_RECORD][:n_records]
    ms = (ts_sub & 0xFFFF).astype(np.float64)
    us = ((ts_sub >> 16) & 0xFFFF).astype(np.float64)
    return ts_sec + ms / 1_000.0 + us / 1_000_000.0


# ---------------------------------------------------------------------------
# Per-camera context
# ---------------------------------------------------------------------------
@dataclass
class CameraContext:
    """All the per-camera knobs the hypotheses need."""
    recording_date: str
    case_no: int
    camera_name: str
    group_name: str
    old_path: Path
    new_path: Path
    pre_roll: int
    t_cam: float                      # = t_seq[0]
    source_fps: float
    idx_frames: int
    old_nb_frames: int
    new_nb_frames: int
    old_fps: float
    new_fps: float
    t_seq: np.ndarray = field(default_factory=lambda: np.empty(0))


# ---------------------------------------------------------------------------
# Core mapping f: SEQ frame -> NEW MP4 frame
# ---------------------------------------------------------------------------
def _f_seq_to_new(K: int, ctx: CameraContext) -> int:
    """Apply the NEW exporter's documented mapping for SEQ frame K -> NEW j.

    j = pre_roll + round((t_seq[K] - t_seq[0]) * 30)

    K is clamped to the valid IDX range; the caller is responsible for
    deciding whether out-of-range j values should be filtered.
    """
    if ctx.idx_frames <= 0:
        return -1
    Kc = max(0, min(int(K), ctx.idx_frames - 1))
    return ctx.pre_roll + int(round((ctx.t_seq[Kc] - ctx.t_cam) * TARGET_FPS))


# ---------------------------------------------------------------------------
# g hypotheses: OLD MP4 frame -> SEQ frame index
# ---------------------------------------------------------------------------
def _g_identity(i: int, ctx: CameraContext) -> int:
    return i


def _g_fps_scale_30(i: int, ctx: CameraContext) -> int:
    return int(round(i * ctx.source_fps / TARGET_FPS))


def _g_fps_scale_oldfps(i: int, ctx: CameraContext) -> int:
    if ctx.old_fps <= 0:
        return i
    return int(round(i * ctx.source_fps / ctx.old_fps))


def _g_shift_plus1(i: int, ctx: CameraContext) -> int:
    return i + 1


def _g_shift_minus1(i: int, ctx: CameraContext) -> int:
    return i - 1


def _g_pre_roll(i: int, ctx: CameraContext) -> int:
    return i - ctx.pre_roll


def _make_learned_g(a: float, b: float):
    """Build a learned-linear g(i) = round(a*i + b)."""
    def _g(i: int, _ctx: CameraContext) -> int:
        return int(round(a * i + b))
    return _g


# Order matters only for printing; not for correctness.
G_HYPOTHESES: list[tuple[str, callable]] = [  # type: ignore[type-arg]
    ("g_identity",         _g_identity),
    ("g_fps_scale_30",     _g_fps_scale_30),
    ("g_fps_scale_oldfps", _g_fps_scale_oldfps),
    ("g_shift_plus1",      _g_shift_plus1),
    ("g_shift_minus1",     _g_shift_minus1),
    ("g_pre_roll",         _g_pre_roll),
]
LEARNED_NAME = "g_linear"


# ---------------------------------------------------------------------------
# Frame extraction + dHash (kept here so this script is self-contained)
# ---------------------------------------------------------------------------
def _resolve_tool(name: str) -> str | None:
    p = shutil.which(name)
    if p:
        return p
    for c in (rf"C:\Program Files\ffmpeg\bin\{name}.exe",
              rf"C:\ffmpeg\bin\{name}.exe",
              rf"C:\Program Files (x86)\ffmpeg\bin\{name}.exe"):
        if Path(c).exists():
            return c
    return None


def _extract_window(mp4: Path, t_seek: float, n_frames: int, ffmpeg: str) -> np.ndarray | None:
    """Extract ``n_frames`` consecutive grayscale 17x16 frames starting near ``t_seek``.

    Two-pass seek (fast keyframe + precise) for frame-accurate output.
    """
    if n_frames <= 0:
        return None
    lead = 2.0
    pre = max(0.0, t_seek - lead)
    cmd = [
        ffmpeg, "-hide_banner", "-loglevel", "error",
        "-ss", f"{pre:.4f}",
        "-i", str(mp4),
        "-ss", f"{t_seek - pre:.4f}",
        "-an",
        "-frames:v", str(n_frames),
        "-vf", f"scale={_DHASH_W}:{_DHASH_H},format=gray",
        "-f", "rawvideo", "-pix_fmt", "gray", "pipe:1",
    ]
    try:
        proc = subprocess.run(cmd, capture_output=True, timeout=60)
    except (subprocess.TimeoutExpired, OSError):
        return None
    if proc.returncode != 0:
        return None
    n_got = len(proc.stdout) // _DHASH_BYTES
    if n_got == 0:
        return None
    return np.frombuffer(proc.stdout[: n_got * _DHASH_BYTES], dtype=np.uint8).reshape(
        n_got, _DHASH_H, _DHASH_W
    )


def _dhash_batch(frames: np.ndarray) -> list[int]:
    diff = (frames[:, :, 1:] > frames[:, :, :-1]).reshape(frames.shape[0], -1)
    packed = np.packbits(diff.astype(np.uint8), axis=1)
    return [int.from_bytes(row.tobytes(), "big") for row in packed]


def _hamming(a: int, b: int) -> int:
    return (int(a) ^ int(b)).bit_count()


# ---------------------------------------------------------------------------
# Path / DB lookup helpers
# ---------------------------------------------------------------------------
def _camera_group(camera: str) -> str:
    if camera in GROUP_A: return "A"
    if camera in GROUP_B: return "B"
    if camera in SOLO_CAMERAS: return "SOLO"
    return "UNKNOWN"


def _ffprobe_basic(mp4: Path, ffprobe: str) -> tuple[int, float] | None:
    """Return (nb_frames, fps) for ``mp4`` or None on failure."""
    cmd = [
        ffprobe, "-v", "error", "-select_streams", "v:0",
        "-show_entries", "stream=nb_frames,avg_frame_rate,duration",
        "-of", "json", str(mp4),
    ]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    except (subprocess.TimeoutExpired, OSError):
        return None
    if proc.returncode != 0:
        return None
    data = json.loads(proc.stdout or "{}")
    s = (data.get("streams") or [{}])[0]
    afr = s.get("avg_frame_rate", "0/1")
    if "/" in afr:
        num, den = afr.split("/", 1)
        fps = float(num) / float(den) if float(den) else 0.0
    else:
        fps = float(afr) if afr else 0.0
    try:
        nb = int(s.get("nb_frames") or 0)
    except (TypeError, ValueError):
        nb = 0
    if nb == 0:
        try:
            dur = float(s.get("duration") or 0.0)
            nb = int(round(dur * fps)) if fps else 0
        except ValueError:
            nb = 0
    return nb, fps


def _build_seq_idx_path(seq_root: Path, rec_date: str, case_no: int, camera: str) -> Path | None:
    """Find the .seq.idx for a (date, case, camera) tuple under SEQ_ROOT."""
    yy = rec_date[2:4]
    mm = rec_date[5:7]
    dd = rec_date[8:10]
    base = seq_root / f"DATA_{yy}-{mm}-{dd}" / f"Case{case_no}"
    cam_dir = base / camera
    if not cam_dir.is_dir():
        for child in base.iterdir() if base.is_dir() else []:
            if child.is_dir() and child.name.rstrip("_JUNKjunk") == camera:
                cam_dir = child
                break
        else:
            return None
    seqs = list(cam_dir.glob("*.seq"))
    if not seqs:
        return None
    idx = Path(str(seqs[0]) + ".idx")
    return idx if idx.exists() else None


def _new_mp4(new_root: Path, rec_date: str, case_no: int, camera: str) -> Path | None:
    yy, mm, dd = rec_date[2:4], rec_date[5:7], rec_date[8:10]
    cam_dir = new_root / f"DATA_{yy}-{mm}-{dd}" / f"Case{case_no}" / camera
    if not cam_dir.is_dir():
        return None
    cands = [p for p in cam_dir.glob("*.mp4") if "_NOT_SYNCABLE" not in p.stem.upper()]
    return sorted(cands)[0] if cands else None


def _old_mp4(old_root: Path, rec_date: str, case_no: int, camera: str) -> Path | None:
    yy, mm, dd = rec_date[2:4], rec_date[5:7], rec_date[8:10]
    cam_dir = old_root / f"DATA_{yy}-{mm}-{dd}" / f"Case{case_no}" / camera
    if not cam_dir.is_dir():
        return None
    cands = list(cam_dir.glob("*.mp4"))
    return sorted(cands)[0] if cands else None


# ---------------------------------------------------------------------------
# Per-camera validation
# ---------------------------------------------------------------------------
def _pick_anchors(ctx: CameraContext, n_anchors: int) -> list[int]:
    """Evenly-spaced anchors in OLD frame space, avoiding the first/last 5%."""
    n_old = ctx.old_nb_frames
    if n_old <= 0:
        return []
    lo = int(n_old * 0.05)
    hi = int(n_old * 0.95)
    if hi <= lo:
        return []
    if n_anchors == 1:
        return [(lo + hi) // 2]
    step = (hi - lo) / (n_anchors - 1)
    out = []
    for k in range(n_anchors):
        i = int(round(lo + k * step))
        # Stay within OLD MP4's valid index range.
        i = max(0, min(i, ctx.old_nb_frames - 1))
        out.append(i)
    return out


def _fit_learned_linear(anchor_results: list[dict]) -> tuple[float, float] | None:
    """Fit `K = a*i + b` from anchors with a clean empirical K_empirical.

    Returns None if there are fewer than 3 usable points.
    """
    pts: list[tuple[int, int]] = []
    for anc in anchor_results:
        K_emp = anc.get("K_empirical")
        h_emp = anc.get("hamming_empirical")
        if K_emp is None or h_emp is None:
            continue
        if h_emp > _GOOD_THRESHOLD_BITS * 2:
            continue
        pts.append((int(anc["i_old"]), int(K_emp)))
    if len(pts) < 3:
        return None
    xs = np.array([p[0] for p in pts], dtype=np.float64)
    ys = np.array([p[1] for p in pts], dtype=np.float64)
    a, b = np.polyfit(xs, ys, 1)
    return float(a), float(b)


def _evaluate_one_anchor(
    ctx: CameraContext,
    i_old: int,
    ffmpeg: str,
    local_radius: int,
    search_radius_seq: int,
    hypotheses: list[tuple[str, callable]],  # type: ignore[type-arg]
) -> dict:
    """Run the full composed validation for a single OLD anchor frame.

    Returns a dict with keys: i_old, h_old (optional), K_empirical,
    j_empirical, hamming_empirical, predictions (per hypothesis), and
    per_formula (per hypothesis metric block). On failure, returns a
    dict containing 'error' and as much partial data as is available.
    """
    t_old = i_old / ctx.old_fps if ctx.old_fps else i_old / TARGET_FPS

    # 1. Extract the OLD anchor frame -> h_old.
    old_frames = _extract_window(ctx.old_path, t_old, 1, ffmpeg)
    if old_frames is None or old_frames.shape[0] == 0:
        return {"i_old": i_old, "error": "OLD_EXTRACT_FAILED"}
    h_old = _dhash_batch(old_frames)[0]

    # 2. Closed-form hypothesis predictions: K_pred, j_pred = f(K_pred).
    predictions: dict[str, dict] = {}
    for name, gfn in hypotheses:
        try:
            K_pred = int(gfn(i_old, ctx))
        except (IndexError, ValueError, OverflowError):
            predictions[name] = {"K_pred": None, "j_pred": -1}
            continue
        if 0 <= K_pred < ctx.idx_frames:
            j_pred = _f_seq_to_new(K_pred, ctx)
        else:
            j_pred = -1
        predictions[name] = {"K_pred": K_pred, "j_pred": j_pred}

    # 3. Search K over [i_old - sR, i_old + sR] (clipped to IDX range).
    K_lo = max(0, i_old - search_radius_seq)
    K_hi = min(ctx.idx_frames - 1, i_old + search_radius_seq)
    if K_hi < K_lo:
        return {
            "i_old": i_old, "error": "EMPTY_SEARCH_RANGE",
            "predictions": predictions,
        }
    search_K = list(range(K_lo, K_hi + 1))
    search_j = [_f_seq_to_new(K, ctx) for K in search_K]

    # 4. Union of all j values (search + hypothesis predictions +/- local_radius).
    candidates: set[int] = set()
    for j in search_j:
        if 0 <= j < ctx.new_nb_frames:
            candidates.add(j)
    for info in predictions.values():
        j = info["j_pred"]
        if j is None or j < 0:
            continue
        lo = max(0, j - local_radius)
        hi = min(ctx.new_nb_frames - 1, j + local_radius)
        candidates.update(range(lo, hi + 1))
    if not candidates:
        return {
            "i_old": i_old, "error": "ALL_PREDICTIONS_OUT_OF_RANGE",
            "predictions": predictions,
        }

    # 5. One ffmpeg burst over the contiguous span [c_min..c_max].
    c_min, c_max = min(candidates), max(candidates)
    n_to_extract = c_max - c_min + 1
    t_seek_new = c_min / TARGET_FPS
    new_frames = _extract_window(ctx.new_path, t_seek_new, n_to_extract, ffmpeg)
    if new_frames is None or new_frames.shape[0] == 0:
        return {
            "i_old": i_old, "error": "NEW_EXTRACT_FAILED",
            "predictions": predictions,
        }
    new_hashes = _dhash_batch(new_frames)
    j_to_hash: dict[int, int] = {
        c_min + k: new_hashes[k] for k in range(min(n_to_extract, len(new_hashes)))
    }

    # 6. Empirical K: the K in the search range that minimizes Hamming.
    # Tie-break by smallest |K - i_old| (prefer the K closest to identity).
    best_tuple: tuple[int, int, int, int] | None = None  # (hamming, |dK|, K, j)
    for K, j in zip(search_K, search_j):
        if j not in j_to_hash:
            continue
        h = _hamming(h_old, j_to_hash[j])
        tup = (h, abs(K - i_old), K, j)
        if best_tuple is None or tup < best_tuple:
            best_tuple = tup
    if best_tuple is None:
        return {
            "i_old": i_old, "error": "NO_SEARCH_HITS",
            "predictions": predictions,
        }
    hamming_empirical, _, K_empirical, j_empirical = best_tuple

    # 7. Per-hypothesis metric block.
    per_formula: dict[str, dict] = {}
    for name, info in predictions.items():
        K_pred = info["K_pred"]
        j_pred = info["j_pred"]
        if j_pred is None or j_pred < 0 or j_pred not in j_to_hash:
            per_formula[name] = {
                "K_pred": K_pred,
                "predicted_j": j_pred if j_pred is not None else -1,
                "hamming_at_predicted": None,
                "min_hamming_local": None,
                "best_offset": None,
                "residual_K": (K_pred - K_empirical) if K_pred is not None else None,
                "out_of_range": True,
            }
            continue
        ham_at = _hamming(h_old, j_to_hash[j_pred])
        best_ham = ham_at
        best_off = 0
        for d in range(-local_radius, local_radius + 1):
            k = j_pred + d
            if k not in j_to_hash:
                continue
            h = _hamming(h_old, j_to_hash[k])
            if h < best_ham:
                best_ham = h
                best_off = d
        per_formula[name] = {
            "K_pred": K_pred,
            "predicted_j": j_pred,
            "hamming_at_predicted": ham_at,
            "min_hamming_local": best_ham,
            "best_offset": best_off,
            "residual_K": (K_pred - K_empirical) if K_pred is not None else None,
            "out_of_range": False,
        }

    return {
        "i_old": i_old,
        "K_empirical": K_empirical,
        "j_empirical": j_empirical,
        "hamming_empirical": hamming_empirical,
        "predictions": predictions,
        "per_formula": per_formula,
    }


def validate_camera(
    ctx: CameraContext, ffmpeg: str, n_anchors: int, local_radius: int,
    search_radius_seq: int,
    extra_predictors: list[tuple[str, callable]] | None = None,  # type: ignore[type-arg]
) -> list[dict]:
    """For each anchor, evaluate every hypothesis under the composed mapping.

    ``extra_predictors`` is appended after the global G_HYPOTHESES list --
    used to inject ``g_linear`` after a per-camera (a, b) fit.
    """
    hypotheses = G_HYPOTHESES + (extra_predictors or [])
    anchors = _pick_anchors(ctx, n_anchors)
    if not anchors:
        return []

    anchor_results: list[dict] = []
    for i_old in anchors:
        anchor_results.append(_evaluate_one_anchor(
            ctx, i_old, ffmpeg, local_radius, search_radius_seq, hypotheses
        ))
    return anchor_results


# ---------------------------------------------------------------------------
# Aggregation + reporting
# ---------------------------------------------------------------------------
def summarise(camera_results: list[dict]) -> dict[str, dict]:
    """Per-hypothesis aggregate metrics across all anchors of one camera."""
    # Discover hypothesis names from the data (includes any runtime-added entries).
    names: list[str] = []
    seen: set[str] = set()
    for anc in camera_results:
        pf = anc.get("per_formula") or {}
        for k in pf:
            if k not in seen:
                seen.add(k)
                names.append(k)
    by_formula: dict[str, list[dict]] = {name: [] for name in names}
    for anc in camera_results:
        pf = anc.get("per_formula") or {}
        for name, info in pf.items():
            if info.get("out_of_range"):
                continue
            if info.get("min_hamming_local") is None:
                continue
            by_formula[name].append(info)

    summary: dict[str, dict] = {}
    for name in by_formula:
        infos = by_formula[name]
        if not infos:
            summary[name] = {"n": 0}
            continue
        min_hams = np.array([i["min_hamming_local"] for i in infos], dtype=np.float64)
        ham_at = np.array([i["hamming_at_predicted"] for i in infos], dtype=np.float64)
        best_offs = np.array([i["best_offset"] for i in infos], dtype=np.int64)
        residuals = np.array(
            [i["residual_K"] for i in infos if i.get("residual_K") is not None],
            dtype=np.int64,
        )
        n_good = int(np.sum(min_hams <= _GOOD_THRESHOLD_BITS))
        n_centred = int(np.sum(np.abs(best_offs) <= _BEST_OFFSET_TOLERANCE))
        n_resid_ok = int(np.sum(np.abs(residuals) <= _RESIDUAL_K_TOLERANCE)) if residuals.size else 0
        summary[name] = {
            "n": len(infos),
            "n_good": n_good,
            "n_centred": n_centred,
            "n_resid_ok": n_resid_ok,
            "mean_min_hamming": float(np.mean(min_hams)),
            "median_min_hamming": float(np.median(min_hams)),
            "mean_ham_at_predicted": float(np.mean(ham_at)),
            "median_best_offset": int(np.median(best_offs)),
            "max_abs_best_offset": int(np.max(np.abs(best_offs))),
            "median_residual_K": int(np.median(residuals)) if residuals.size else 0,
            "max_abs_residual_K": int(np.max(np.abs(residuals))) if residuals.size else -1,
        }
    return summary


def empirical_health(camera_results: list[dict]) -> dict:
    """How clean is the dHash-derived ground truth across this camera's anchors?

    Used both for the per-camera CLExport flag and for trusting g_linear.
    """
    hams = [r["hamming_empirical"] for r in camera_results
            if r.get("hamming_empirical") is not None]
    if not hams:
        return {"n": 0}
    arr = np.array(hams, dtype=np.float64)
    return {
        "n": len(hams),
        "mean": float(np.mean(arr)),
        "median": float(np.median(arr)),
        "max": float(np.max(arr)),
    }


def _verdict(s: dict, n_anchors: int) -> str:
    """Decide a short label for how well a hypothesis fits this camera.

    Surgical scenes are near-static, so the empirical-K column is noise
    dominated. The verdict is therefore driven by j-space metrics (does
    j_pred land near the local Hamming minimum on the NEW MP4?). The
    residual_K column is reported but not used to gate CONFIRMED.
    """
    if not s or s.get("n", 0) == 0:
        return "NO_DATA"
    n = s["n"]
    if n_anchors == 0:
        return "NO_DATA"
    good_frac = s["n_good"] / n
    centred_frac = s["n_centred"] / n
    if (good_frac >= 0.8 and centred_frac >= 0.8
            and s["mean_min_hamming"] <= 12):
        return "CONFIRMED"
    if good_frac >= 0.5 and s["mean_min_hamming"] <= 20:
        return "PLAUSIBLE"
    return "FAILS"


def _formula_order(summary: dict[str, dict]) -> list[str]:
    """Return hypothesis names in display order: G_HYPOTHESES first, then extras."""
    base = [name for name, _ in G_HYPOTHESES]
    extras = [k for k in summary.keys() if k not in base]
    return base + extras


def print_camera_report(
    ctx: CameraContext, results: list[dict], summary: dict[str, dict],
    emp_health: dict, learned_ab: tuple[float, float] | None = None,
    clexport_flag: bool = False,
) -> None:
    print("=" * 102)
    print(f"Camera: {ctx.camera_name}  ({ctx.recording_date} Case{ctx.case_no}, group {ctx.group_name})")
    print(f"  pre_roll={ctx.pre_roll} frames  t_cam={ctx.t_cam:.3f}  "
          f"source_fps={ctx.source_fps:.4f}  idx_frames={ctx.idx_frames}")
    print(f"  OLD: {ctx.old_nb_frames} frames @ {ctx.old_fps:.4f} fps   "
          f"NEW: {ctx.new_nb_frames} frames @ {ctx.new_fps:.4f} fps")
    print(f"  OLD path: {ctx.old_path}")
    print(f"  NEW path: {ctx.new_path}")
    if emp_health.get("n"):
        print(f"  empirical K search: n={emp_health['n']} "
              f"mean_H={emp_health['mean']:.2f} median_H={emp_health['median']:.2f} "
              f"max_H={emp_health['max']:.2f}")
    if learned_ab is not None:
        a, b = learned_ab
        print(f"  g_linear fit:       K = {a:.6f} * i_old + {b:+.3f}")
    if clexport_flag:
        print("  >>> LIKELY_CLEXPORT: no closed-form g hypothesis fits; OLD MP4 "
              "may have been produced by the CLExport fallback path.")

    names = _formula_order(summary)

    # Per-hypothesis summary table.
    print()
    print(f"  {'hypothesis':>22s}  {'n':>3s}  {'good':>4s}  {'centred':>7s}  "
          f"{'resOK':>5s}  {'meanH':>6s}  {'medOff':>6s}  {'medRes':>6s}  "
          f"{'maxRes':>6s}  {'verdict':>10s}")
    n_anch = sum(1 for r in results if "per_formula" in r)
    for name in names:
        s = summary.get(name, {})
        if not s or s.get("n", 0) == 0:
            print(f"  {name:>22s}    -     -        -      -       -       -       -       -  "
                  f"{'NO_DATA':>10s}")
            continue
        print(
            f"  {name:>22s}  {s['n']:>3d}  {s['n_good']:>4d}  {s['n_centred']:>7d}  "
            f"{s['n_resid_ok']:>5d}  {s['mean_min_hamming']:>6.2f}  "
            f"{s['median_best_offset']:>+6d}  {s['median_residual_K']:>+6d}  "
            f"{s['max_abs_residual_K']:>6d}  {_verdict(s, n_anch):>10s}"
        )
    print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def _parse_cases_arg(spec: str) -> list[tuple[str, int]]:
    """Parse a `YYYY-MM-DD:N,YYYY-MM-DD:M,...` --cases value into pairs."""
    out: list[tuple[str, int]] = []
    for tok in spec.split(","):
        tok = tok.strip()
        if not tok:
            continue
        if ":" not in tok:
            raise argparse.ArgumentTypeError(f"Bad case spec '{tok}': expected DATE:N.")
        date, case_str = tok.split(":", 1)
        try:
            out.append((date.strip(), int(case_str)))
        except ValueError as exc:
            raise argparse.ArgumentTypeError(f"Bad case spec '{tok}': {exc}") from exc
    return out


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description=("Validate the composed OLD MP4 -> SEQ -> NEW MP4 frame "
                     "mapping with tight dHash checks."),
    )
    ap.add_argument("--old-root", default=DEFAULT_OLD_ROOT)
    ap.add_argument("--new-root", default=get_mp4_root())
    ap.add_argument("--seq-root", default=get_seq_root())
    ap.add_argument("--db", default=get_db_path())
    grp = ap.add_mutually_exclusive_group(required=True)
    grp.add_argument("--cases", type=_parse_cases_arg, default=None,
                     help="Comma-sep DATE:N pairs, e.g. 2025-10-12:1,2025-09-09:1")
    grp.add_argument("--date", default=None, help="YYYY-MM-DD (single-case mode)")
    ap.add_argument("--case", type=int, default=None,
                    help="Single-case mode: case number (paired with --date).")
    ap.add_argument("--cameras", nargs="*", default=None,
                    help="Restrict to these camera folder names.")
    ap.add_argument("--samples", type=int, default=15,
                    help="Anchor frames per camera (default: 15, spread evenly).")
    ap.add_argument("--local-radius", type=int, default=5,
                    help="Tight verify window radius on NEW MP4 in frames (default: 5).")
    ap.add_argument("--search-radius-seq", type=int, default=_DEFAULT_SEARCH_RADIUS_SEQ,
                    help=("K-space empirical search radius around i_old in SEQ "
                          f"frames (default: {_DEFAULT_SEARCH_RADIUS_SEQ})."))
    ap.add_argument("--hamming-threshold", type=int, default=16,
                    help="PASS if min_hamming_local <= this (default: 16 / 256).")
    ap.add_argument("--out-detailed-csv", default=None,
                    help="Per-anchor per-hypothesis CSV (one row each).")
    ap.add_argument("--out-summary-csv", default=None,
                    help="Per-camera per-hypothesis CSV.")
    ap.add_argument("--out-json", default=None,
                    help="Optional JSON dump path.")
    args = ap.parse_args(argv)
    if args.cases is None:
        if args.case is None:
            ap.error("--date requires --case.")
        args.cases = [(args.date, args.case)]
    return args


def _load_camera_first_times(db_path: str, rec_date: str, case_no: int) -> dict[str, float]:
    """Read seq_enriched.first_frame_time for every camera in this case."""
    out: dict[str, float] = {}
    if not Path(db_path).is_file():
        return out
    with sqlite3.connect(db_path) as conn:
        conn.execute("PRAGMA foreign_keys = ON")
        cur = conn.execute(
            "SELECT camera_name, first_frame_time "
            "FROM seq_enriched WHERE recording_date=? AND case_no=?",
            (rec_date, case_no),
        )
        for cam, t0 in cur.fetchall():
            try:
                t0f = float(t0)
            except (TypeError, ValueError):
                continue
            if _EPOCH_MIN <= t0f <= _EPOCH_MAX:
                out[cam] = t0f
    return out


def _build_context_for_camera(
    args: argparse.Namespace, rec_date: str, case_no: int, camera: str,
    group_t_start: dict[str, float], ffprobe: str,
) -> CameraContext | None:
    """Resolve all per-camera knobs needed before the validation loop."""
    old_root = Path(args.old_root).resolve()
    new_root = Path(args.new_root).resolve()
    seq_root = Path(args.seq_root).resolve()

    grp = _camera_group(camera)
    if grp == "UNKNOWN":
        return None

    old_path = _old_mp4(old_root, rec_date, case_no, camera)
    new_path = _new_mp4(new_root, rec_date, case_no, camera)
    if not old_path or not new_path:
        return None

    idx_path = _build_seq_idx_path(seq_root, rec_date, case_no, camera)
    if idx_path is None:
        return None
    t_seq = parse_idx_timestamps(idx_path)
    if t_seq is None or len(t_seq) == 0:
        return None

    old_basic = _ffprobe_basic(old_path, ffprobe)
    new_basic = _ffprobe_basic(new_path, ffprobe)
    if not old_basic or not new_basic:
        return None

    old_nb, old_fps = old_basic
    new_nb, new_fps = new_basic
    idx_frames = int(len(t_seq))
    t_cam = float(t_seq[0])
    t_last = float(t_seq[-1])
    actual_duration = max(t_last - t_cam, 1e-9)
    source_fps = (idx_frames - 1) / actual_duration
    t_global = group_t_start.get(grp, t_cam)
    pre_roll = int(round((t_cam - t_global) * TARGET_FPS))

    return CameraContext(
        recording_date=rec_date,
        case_no=case_no,
        camera_name=camera,
        group_name=grp,
        old_path=old_path,
        new_path=new_path,
        pre_roll=pre_roll,
        t_cam=t_cam,
        source_fps=source_fps,
        idx_frames=idx_frames,
        old_nb_frames=old_nb,
        new_nb_frames=new_nb,
        old_fps=old_fps,
        new_fps=new_fps,
        t_seq=t_seq,
    )


_DETAILED_CSV_COLS = [
    "recording_date", "case_no", "camera_name", "group_name",
    "i_old", "K_empirical", "j_empirical", "hamming_empirical",
    "hypothesis", "K_pred", "predicted_j",
    "hamming_at_predicted", "min_hamming_local", "best_offset",
    "residual_K",
    "pass_fail", "out_of_range",
]


_SUMMARY_CSV_COLS = [
    "recording_date", "case_no", "camera_name", "group_name",
    "source_fps", "pre_roll", "idx_frames",
    "old_nb_frames", "new_nb_frames", "old_fps",
    "learned_a", "learned_b",
    "empirical_mean_H", "empirical_median_H", "empirical_max_H",
    "clexport_flag",
    "hypothesis", "n", "n_good", "n_centred", "n_resid_ok",
    "mean_min_hamming", "median_min_hamming",
    "mean_ham_at_predicted",
    "median_best_offset", "max_abs_best_offset",
    "median_residual_K", "max_abs_residual_K",
    "verdict",
]


def _write_detailed_csv(rows: list[dict], path: Path) -> None:
    import csv
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=_DETAILED_CSV_COLS)
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in _DETAILED_CSV_COLS})


def _write_summary_csv(rows: list[dict], path: Path) -> None:
    import csv
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=_SUMMARY_CSV_COLS)
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in _SUMMARY_CSV_COLS})


def _aggregate_and_answer(summary_rows: list[dict], threshold: int) -> None:
    """Aggregate per-camera summary rows and call the winning g hypothesis."""
    if not summary_rows:
        print("No summary rows to aggregate.")
        return

    hypotheses = sorted({r["hypothesis"] for r in summary_rows})

    # ------- Headline: which hypothesis confirms most often?
    print("=" * 102)
    print("AGGREGATE ACROSS ALL (case, camera) PAIRS")
    print("=" * 102)
    print(f"  {'hypothesis':>22s}  {'n_pairs':>7s}  {'n_CONFIRM':>9s}  {'n_PLAUS':>7s}  "
          f"{'n_FAILS':>7s}  {'mean_minH':>9s}  {'p95_minH':>9s}  {'med_|resK|':>10s}")
    overall: dict[str, dict] = {}
    for f in hypotheses:
        rows = [r for r in summary_rows if r["hypothesis"] == f]
        n_pairs = len(rows)
        if n_pairs == 0:
            continue
        verdicts = [r["verdict"] for r in rows]
        mins = np.array([r["mean_min_hamming"] for r in rows
                         if r.get("mean_min_hamming") is not None],
                        dtype=np.float64)
        maxres = np.array([abs(int(r["max_abs_residual_K"])) for r in rows
                           if r.get("max_abs_residual_K") not in (None, "")],
                          dtype=np.float64)
        overall[f] = {
            "n_pairs": n_pairs,
            "n_CONFIRMED": verdicts.count("CONFIRMED"),
            "n_PLAUSIBLE": verdicts.count("PLAUSIBLE"),
            "n_FAILS":     verdicts.count("FAILS"),
            "mean_minH":   float(np.mean(mins)) if mins.size else float("nan"),
            "p95_minH":    float(np.percentile(mins, 95)) if mins.size else float("nan"),
            "median_maxresK": float(np.median(maxres)) if maxres.size else float("nan"),
        }
        print(f"  {f:>22s}  {n_pairs:>7d}  {overall[f]['n_CONFIRMED']:>9d}  "
              f"{overall[f]['n_PLAUSIBLE']:>7d}  {overall[f]['n_FAILS']:>7d}  "
              f"{overall[f]['mean_minH']:>9.2f}  {overall[f]['p95_minH']:>9.2f}  "
              f"{overall[f]['median_maxresK']:>10.2f}")
    print()

    # ------- Pick the overall winner.
    if overall:
        winner = max(
            overall.items(),
            key=lambda kv: (kv[1]["n_CONFIRMED"], -kv[1]["mean_minH"]),
        )
        print(f"WINNER: {winner[0]}  ({winner[1]['n_CONFIRMED']} CONFIRMED / "
              f"{winner[1]['n_pairs']} pairs, mean_minH={winner[1]['mean_minH']:.2f})")
        print()

    # ------- Per-camera g_linear slope/intercept stability across cases.
    print("Per-camera g_linear slope/intercept across cases:")
    print(f"  {'camera':>22s}  {'n_cases':>7s}  {'a_range':>22s}  {'b_range':>22s}")
    by_camera: dict[str, list[dict]] = {}
    for r in summary_rows:
        # Pick one row per (case, camera) -- g_identity is always present.
        if r["hypothesis"] != "g_identity":
            continue
        by_camera.setdefault(r["camera_name"], []).append(r)
    for cam, rows in sorted(by_camera.items()):
        if not rows:
            continue
        a_learned = [float(r["learned_a"]) for r in rows
                     if r.get("learned_a") not in (None, "")]
        b_learned = [float(r["learned_b"]) for r in rows
                     if r.get("learned_b") not in (None, "")]
        fmt_a = (f"{min(a_learned):.6f}..{max(a_learned):.6f}"
                 if a_learned else "-")
        fmt_b = (f"{min(b_learned):.2f}..{max(b_learned):.2f}"
                 if b_learned else "-")
        print(f"  {cam:>22s}  {len(rows):>7d}  {fmt_a:>22s}  {fmt_b:>22s}")
    print()

    # ------- CLExport-suspect cameras.
    flagged = [(r["recording_date"], r["case_no"], r["camera_name"])
               for r in summary_rows
               if r["hypothesis"] == "g_identity" and str(r.get("clexport_flag")) == "1"]
    if flagged:
        print(f"CLExport-suspect (no closed-form hypothesis fits) -- "
              f"{len(set(flagged))} (case, camera) pairs:")
        for d, c, cam in sorted(set(flagged)):
            print(f"  {d} Case{c} {cam}")
        print()

    # ------- dHash threshold calibration for the winning hypothesis.
    if overall:
        primary = winner[0]
        primary_rows = [r for r in summary_rows if r["hypothesis"] == primary]
        if primary_rows:
            meds = np.array([r["median_min_hamming"] for r in primary_rows
                             if r.get("median_min_hamming") is not None],
                            dtype=np.float64)
            means = np.array([r["mean_min_hamming"] for r in primary_rows
                              if r.get("mean_min_hamming") is not None],
                             dtype=np.float64)
            print(f"dHash distribution under winning hypothesis '{primary}':")
            print(f"  per-(case,camera) median min_hamming:  "
                  f"mean={float(np.mean(meds)):.2f}  median={float(np.median(meds)):.2f}  "
                  f"p90={float(np.percentile(meds, 90)):.2f}  "
                  f"p99={float(np.percentile(meds, 99)):.2f}  "
                  f"max={float(np.max(meds)):.2f}")
            print(f"  per-(case,camera) mean min_hamming:    "
                  f"mean={float(np.mean(means)):.2f}  median={float(np.median(means)):.2f}  "
                  f"p90={float(np.percentile(means, 90)):.2f}  "
                  f"p99={float(np.percentile(means, 99)):.2f}  "
                  f"max={float(np.max(means)):.2f}")
            print(f"  PASS threshold (--hamming-threshold)  = {threshold} / 256")
            n_pairs_failing_thresh = int(np.sum(meds > threshold))
            print(f"  pairs with median(min_hamming) > threshold: "
                  f"{n_pairs_failing_thresh} / {len(meds)}")
    print()


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)

    ffmpeg = _resolve_tool("ffmpeg")
    ffprobe = _resolve_tool("ffprobe")
    if not ffmpeg or not ffprobe:
        print("ffmpeg / ffprobe not found on PATH.", file=sys.stderr)
        return 2

    cameras_filter: set[str] | None = set(args.cameras) if args.cameras else None
    detailed_rows: list[dict] = []
    summary_rows: list[dict] = []
    json_dump: list[dict] = []
    t_start = time.time()

    for rec_date, case_no in args.cases:
        # Group-wise t_global_start for this case (from DB).
        cam_first = _load_camera_first_times(args.db, rec_date, case_no)
        if not cam_first:
            print(f"[skip case] {rec_date} Case{case_no}: no seq_enriched timing rows")
            continue
        group_t_start: dict[str, float] = {}
        for cam, t0 in cam_first.items():
            grp = _camera_group(cam)
            if grp == "UNKNOWN":
                continue
            if t0 < group_t_start.get(grp, float("inf")):
                group_t_start[grp] = t0

        print(f"\n>>>>>> CASE {rec_date} Case{case_no} <<<<<<")
        for camera in sorted(cam_first.keys()):
            if cameras_filter is not None and camera not in cameras_filter:
                continue
            ctx = _build_context_for_camera(args, rec_date, case_no, camera, group_t_start, ffprobe)
            if ctx is None:
                print(f"[skip] {camera}: setup failed (missing MP4/IDX/probe)")
                continue

            # Pass 1: closed-form hypotheses + empirical K search.
            results = validate_camera(
                ctx, ffmpeg, args.samples, args.local_radius, args.search_radius_seq,
            )

            # Fit g_linear from clean empirical K_empirical points; re-run
            # the per-hypothesis evaluator once g_linear is known so it
            # appears in the per-anchor table. We only need the per_formula
            # block for g_linear, so we re-evaluate cheaply: the burst
            # window already covers the relevant span -- but it's simpler
            # to just call _evaluate_one_anchor with the g_linear predictor
            # added.
            learned_ab = _fit_learned_linear(results)
            if learned_ab is not None:
                a, b = learned_ab
                extra = [(LEARNED_NAME, _make_learned_g(a, b))]
                # Rerun only the hypothesis evaluation; we keep K_empirical
                # from pass 1 by stitching the new per_formula[g_linear]
                # block onto each anchor.
                for anc in results:
                    if "error" in anc:
                        continue
                    new_anc = _evaluate_one_anchor(
                        ctx, anc["i_old"], ffmpeg, args.local_radius,
                        args.search_radius_seq, extra,
                    )
                    pf_new = new_anc.get("per_formula") or {}
                    if LEARNED_NAME in pf_new:
                        anc.setdefault("per_formula", {})[LEARNED_NAME] = pf_new[LEARNED_NAME]
                        anc.setdefault("predictions", {})[LEARNED_NAME] = (
                            new_anc.get("predictions") or {}
                        ).get(LEARNED_NAME, {})

            summary = summarise(results)
            emp = empirical_health(results)

            # CLExport flag: every closed-form g hypothesis is FAILS (not
            # even PLAUSIBLE) AND the empirical search still found a
            # clean match. That means the OLD MP4 has frames somewhere
            # in the search radius (so mapping is recoverable) but not
            # at any closed-form K.
            closed_form_names = [n for n, _ in G_HYPOTHESES]
            any_at_least_plausible = any(
                _verdict(summary.get(n, {}), args.samples) in ("CONFIRMED", "PLAUSIBLE")
                for n in closed_form_names
            )
            clexport_flag = (
                (not any_at_least_plausible)
                and emp.get("n", 0) > 0
                and emp.get("median", 1e9) <= _CLEXPORT_FLAG_THRESHOLD_BITS
            )

            print_camera_report(ctx, results, summary, emp, learned_ab, clexport_flag)

            # ----- Per-anchor detailed rows -----
            for anc in results:
                if "per_formula" not in anc:
                    continue
                i_old = anc["i_old"]
                K_emp = anc.get("K_empirical")
                j_emp = anc.get("j_empirical")
                h_emp = anc.get("hamming_empirical")
                for fname, info in anc["per_formula"].items():
                    K_pred = info.get("K_pred")
                    pred_j = info.get("predicted_j")
                    min_h = info.get("min_hamming_local")
                    ham_at = info.get("hamming_at_predicted")
                    best_off = info.get("best_offset")
                    resid_K = info.get("residual_K")
                    is_oor = info.get("out_of_range", False)
                    if is_oor or min_h is None:
                        pf = "OOR"
                    elif (min_h <= args.hamming_threshold
                          and resid_K is not None
                          and abs(resid_K) <= _RESIDUAL_K_TOLERANCE):
                        pf = "PASS"
                    elif min_h <= args.hamming_threshold:
                        pf = "WRONG_K"
                    else:
                        pf = "VERIFY_FAILED"
                    detailed_rows.append({
                        "recording_date": rec_date,
                        "case_no": case_no,
                        "camera_name": camera,
                        "group_name": ctx.group_name,
                        "i_old": i_old,
                        "K_empirical": K_emp if K_emp is not None else "",
                        "j_empirical": j_emp if j_emp is not None else "",
                        "hamming_empirical": h_emp if h_emp is not None else "",
                        "hypothesis": fname,
                        "K_pred": K_pred if K_pred is not None else "",
                        "predicted_j": pred_j if pred_j is not None else "",
                        "hamming_at_predicted": ham_at if ham_at is not None else "",
                        "min_hamming_local": min_h if min_h is not None else "",
                        "best_offset": best_off if best_off is not None else "",
                        "residual_K": resid_K if resid_K is not None else "",
                        "pass_fail": pf,
                        "out_of_range": "1" if is_oor else "0",
                    })

            # ----- Per-camera summary rows -----
            n_anch = sum(1 for r in results if "per_formula" in r)
            for fname, s in summary.items():
                if not s or s.get("n", 0) == 0:
                    continue
                summary_rows.append({
                    "recording_date": rec_date,
                    "case_no": case_no,
                    "camera_name": camera,
                    "group_name": ctx.group_name,
                    "source_fps": f"{ctx.source_fps:.6f}",
                    "pre_roll": ctx.pre_roll,
                    "idx_frames": ctx.idx_frames,
                    "old_nb_frames": ctx.old_nb_frames,
                    "new_nb_frames": ctx.new_nb_frames,
                    "old_fps": f"{ctx.old_fps:.6f}",
                    "learned_a": f"{learned_ab[0]:.8f}" if learned_ab else "",
                    "learned_b": f"{learned_ab[1]:.3f}" if learned_ab else "",
                    "empirical_mean_H": f"{emp['mean']:.4f}" if emp.get("n") else "",
                    "empirical_median_H": f"{emp['median']:.4f}" if emp.get("n") else "",
                    "empirical_max_H": f"{emp['max']:.4f}" if emp.get("n") else "",
                    "clexport_flag": "1" if clexport_flag else "0",
                    "hypothesis": fname,
                    "n": s["n"],
                    "n_good": s["n_good"],
                    "n_centred": s["n_centred"],
                    "n_resid_ok": s["n_resid_ok"],
                    "mean_min_hamming":     f"{s['mean_min_hamming']:.4f}",
                    "median_min_hamming":   f"{s['median_min_hamming']:.4f}",
                    "mean_ham_at_predicted": f"{s['mean_ham_at_predicted']:.4f}",
                    "median_best_offset":   s["median_best_offset"],
                    "max_abs_best_offset":  s["max_abs_best_offset"],
                    "median_residual_K":    s["median_residual_K"],
                    "max_abs_residual_K":   s["max_abs_residual_K"],
                    "verdict":              _verdict(s, n_anch),
                })

            json_dump.append({
                "recording_date": rec_date,
                "case_no": case_no,
                "camera": camera,
                "group": ctx.group_name,
                "pre_roll": ctx.pre_roll,
                "source_fps": ctx.source_fps,
                "idx_frames": ctx.idx_frames,
                "old_nb_frames": ctx.old_nb_frames,
                "new_nb_frames": ctx.new_nb_frames,
                "old_fps": ctx.old_fps,
                "new_fps": ctx.new_fps,
                "learned_ab": list(learned_ab) if learned_ab else None,
                "empirical_health": emp,
                "clexport_flag": clexport_flag,
                "anchors": results,
                "summary": summary,
            })

    # ----- Build numeric fields back into summary_rows for analysis -----
    for r in summary_rows:
        try:
            r["mean_min_hamming"] = float(r["mean_min_hamming"])
            r["median_min_hamming"] = float(r["median_min_hamming"])
        except (TypeError, ValueError):
            pass

    if args.out_detailed_csv:
        _write_detailed_csv(detailed_rows, Path(args.out_detailed_csv).resolve())
        print(f"Wrote detailed CSV ({len(detailed_rows)} rows) "
              f"to {Path(args.out_detailed_csv).resolve()}")
    if args.out_summary_csv:
        _write_summary_csv(summary_rows, Path(args.out_summary_csv).resolve())
        print(f"Wrote summary CSV ({len(summary_rows)} rows) "
              f"to {Path(args.out_summary_csv).resolve()}")
    if args.out_json:
        op = Path(args.out_json).resolve()
        op.parent.mkdir(parents=True, exist_ok=True)
        with op.open("w", encoding="utf-8") as fh:
            json.dump({
                "cases": [list(p) for p in args.cases],
                "samples": args.samples,
                "local_radius": args.local_radius,
                "search_radius_seq": args.search_radius_seq,
                "hamming_threshold": args.hamming_threshold,
                "per_camera": json_dump,
            }, fh, indent=2)
        print(f"Wrote JSON dump to {op}")

    _aggregate_and_answer(summary_rows, args.hamming_threshold)
    print(f"Done in {time.time() - t_start:.1f}s.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
