"""
Data Models for Manual Camera Synchronization

This module defines the core entities used in the multi-camera synchronization system:
- Camera: Individual video camera/angle with sync state
- Case: Surgical case with metadata
- CameraMetadata: Database record for camera file
- SyncAdjustment: Pending sync offset changes (in-memory tracking)

Created for feature: 1-multimpv-db-controls (Manual Camera Synchronization)
Author: Generated by Claude Code
Date: 2026-01-12
"""

from dataclasses import dataclass, field
from typing import Optional, Tuple, List
from datetime import datetime
import subprocess


@dataclass
class Camera:
    """
    Represents a single video camera/angle in a multi-camera setup.

    This is the PRIMARY entity for the sync system. Each Camera tracks:
    - Video playback state (MPV process, current timestamp, pause state)
    - Sync state (offset, sync delta, sync status)
    - UI state (selection, reference designation)

    Lifecycle: Created when videos are loaded, destroyed when application closes.
    """

    # Identity
    name: str  # e.g., "Cart_Center", "Monitor", "Room_Left"
    file_path: str  # Absolute path to video file
    case_id: Tuple[str, int]  # (recording_date, case_no) for DB lookups

    # Playback State
    mpv_process: subprocess.Popen  # MPV subprocess handle
    ipc_pipe_path: str  # Named pipe path for IPC
    current_timestamp: float = 0.0  # Current playback position (seconds)
    duration: float = 0.0  # Video duration (seconds)
    is_paused: bool = False  # Individual pause state

    # Sync State
    offset_seconds: float = 0.0  # Applied sync offset (from DB or user adjustment)
    offset_modified: bool = False  # True if offset changed since last DB save
    sync_delta: float = 0.0  # Calculated delta from reference camera (seconds)
    sync_status: str = "synced"  # "synced" | "out_of_sync"
    sync_status_text: str = "[OK] Synced"  # Display text

    # UI State
    is_selected: bool = False  # Currently selected in sync panel list
    is_reference: bool = False  # Designated as reference camera

    def __post_init__(self):
        """Validate attributes after initialization"""
        # Round offset to 1 decimal place (0.1s increments)
        self.offset_seconds = round(self.offset_seconds, 1)

        # Validate offset range (±300 seconds = ±5 minutes)
        if not (-300.0 <= self.offset_seconds <= 300.0):
            raise ValueError(
                f"Offset {self.offset_seconds}s outside allowed range (±300s)"
            )

        # Validate timestamp
        if self.current_timestamp < 0:
            raise ValueError(
                f"Timestamp cannot be negative: {self.current_timestamp}"
            )

    def update_sync_status(self, reference_timestamp: float, tolerance: float = 0.3):
        """
        Calculate sync status relative to reference camera.

        Args:
            reference_timestamp: Current timestamp of reference camera
            tolerance: Sync tolerance in seconds (default: 0.3s per REQ-1.1)

        Updates:
            - self.sync_delta: Delta from reference in seconds
            - self.sync_status: "synced" or "out_of_sync"
            - self.sync_status_text: Display string with delta
        """
        # Calculate delta (accounting for applied offset)
        self.sync_delta = (
            self.current_timestamp - reference_timestamp + self.offset_seconds
        )

        # Classify sync status
        if abs(self.sync_delta) <= tolerance:
            self.sync_status = "synced"
            self.sync_status_text = "[OK] Synced"
        else:
            self.sync_status = "out_of_sync"
            if self.sync_delta > 0:
                self.sync_status_text = f"+{self.sync_delta:.1f}s ahead"
            else:
                self.sync_status_text = f"{self.sync_delta:.1f}s behind"


@dataclass
class CameraMetadata:
    """
    Metadata for a camera file associated with a case.

    Loaded from `mp4_status` database table before video initialization.
    Used to populate Camera entities.

    Lifecycle: Loaded when case selected, used to initialize Camera objects.
    """

    camera_name: str  # e.g., "Cart_Center"
    file_path: str  # Absolute path to video file
    duration: float  # Video duration in seconds
    file_size: int  # File size in bytes
    offset_seconds: float = 0.0  # Saved sync offset from DB (or 0.0)
    file_exists: bool = True  # Default to True, trusted from DB
    case_id: Optional[Tuple[str, int]] = None # (date, case_no)

    def __post_init__(self):
        """Validate attributes"""
        # Round offset to 1 decimal place (0.1s increments)
        self.offset_seconds = round(self.offset_seconds, 1)

        # Validate file format
        valid_extensions = ('.mp4', '.MP4', '.mkv', '.MKV', '.avi', '.AVI')
        if not self.file_path.endswith(valid_extensions):
            raise ValueError(f"Unsupported video format: {self.file_path}")

        # Validate offset range
        if not (-300.0 <= self.offset_seconds <= 300.0):
            raise ValueError(
                f"Offset {self.offset_seconds}s outside allowed range (±300s)"
            )


@dataclass
class Case:
    """
    Represents a surgical case with metadata and associated camera recordings.

    Loaded from database when user selects case in browser.

    Lifecycle: Created from DB query, exists for session duration.
    """

    # Identity
    recording_date: str  # ISO format: "2023-05-15"
    case_no: int  # Case number for that date

    # Metadata
    room: str = ""  # Operating room identifier (e.g., "Room 8")
    anesthesiologist_name: str = ""  # Full name of attending
    camera_count: int = 0  # Number of available cameras
    total_duration: float = 0.0  # Longest camera duration (seconds)

    # Relationships
    cameras: List[CameraMetadata] = field(default_factory=list)  # Available cameras

    def __post_init__(self):
        """Validate case attributes"""
        # Validate date format
        import re
        if not re.match(r'^\d{4}-\d{2}-\d{2}$', self.recording_date):
            raise ValueError(
                f"Invalid date format: {self.recording_date} (expected YYYY-MM-DD)"
            )

        # Validate case number
        if self.case_no <= 0:
            raise ValueError(f"Case number must be positive: {self.case_no}")

        # Validate camera count consistency (only if cameras are populated)
        if self.cameras and self.camera_count != len(self.cameras):
            raise ValueError(
                f"Camera count mismatch: {self.camera_count} != {len(self.cameras)}"
            )

        # Validate camera count range (only if count > 0)
        if self.camera_count > 9:
             raise ValueError(
                f"Camera count {self.camera_count} outside allowed range (1-9)"
            )


@dataclass
class SyncAdjustment:
    """
    Tracks pending sync offset changes before database commit.

    Used for confirmation dialog display. This entity is IN-MEMORY ONLY and does
    not persist to database until user explicitly confirms.

    Lifecycle: Created when user clicks nudge button, cleared after DB save or cancel.
    """

    camera_name: str  # Camera identifier
    case_id: Tuple[str, int]  # (recording_date, case_no)
    old_offset: float  # Original offset from database
    new_offset: float  # User-adjusted offset (current value)
    timestamp: datetime = field(default_factory=datetime.now)  # When adjusted

    @property
    def delta(self) -> float:
        """Calculate offset change"""
        return self.new_offset - self.old_offset

    def __str__(self) -> str:
        """Format for display in confirmation dialog"""
        return f"{self.camera_name}: {self.new_offset:+.1f}s (was {self.old_offset:+.1f}s)"


# Validation constants (used in models and UI)
OFFSET_MIN = -300.0  # -5 minutes
OFFSET_MAX = 300.0  # +5 minutes
SYNC_TOLERANCE = 0.3  # ±0.3 seconds per REQ-1.1
MAX_CAMERAS = 9  # Maximum cameras per case per REQ-2.4
